/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingQualityRouteImport } from './routes/mapping-quality'
import { Route as ProjectSetupRouteImport } from './routes/project-setup'
import { Route as RulesRouteImport } from './routes/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingQualityRoute = MappingQualityRouteImport.update({
  id: '/mapping-quality',
  path: '/mapping-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSetupRoute = ProjectSetupRouteImport.update({
  id: '/project-setup',
  path: '/project-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/project-setup'
    | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/project-setup'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/project-setup'
    | '/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataSourcesRoute: typeof DataSourcesRoute
  LoginRoute: typeof LoginRoute
  MappingQualityRoute: typeof MappingQualityRoute
  ProjectSetupRoute: typeof ProjectSetupRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping-quality': {
      id: '/mapping-quality'
      path: '/mapping-quality'
      fullPath: '/mapping-quality'
      preLoaderRoute: typeof MappingQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-setup': {
      id: '/project-setup'
      path: '/project-setup'
      fullPath: '/project-setup'
      preLoaderRoute: typeof ProjectSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataSourcesRoute: DataSourcesRoute,
  LoginRoute: LoginRoute,
  MappingQualityRoute: MappingQualityRoute,
  ProjectSetupRoute: ProjectSetupRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
