/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountResultsRouteImport } from './routes/account-results'
import { Route as AgentConfigurationRouteImport } from './routes/agent-configuration'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingQualityRouteImport } from './routes/mapping-quality'
import { Route as NewPatternsRouteImport } from './routes/new-patterns'
import { Route as PocRunsRouteImport } from './routes/poc-runs'
import { Route as ProjectSetupRouteImport } from './routes/project-setup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WorkflowDesignerRouteImport } from './routes/workflow-designer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResultsRoute = AccountResultsRouteImport.update({
  id: '/account-results',
  path: '/account-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConfigurationRoute = AgentConfigurationRouteImport.update({
  id: '/agent-configuration',
  path: '/agent-configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingQualityRoute = MappingQualityRouteImport.update({
  id: '/mapping-quality',
  path: '/mapping-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatternsRoute = NewPatternsRouteImport.update({
  id: '/new-patterns',
  path: '/new-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PocRunsRoute = PocRunsRouteImport.update({
  id: '/poc-runs',
  path: '/poc-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSetupRoute = ProjectSetupRouteImport.update({
  id: '/project-setup',
  path: '/project-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowDesignerRoute = WorkflowDesignerRouteImport.update({
  id: '/workflow-designer',
  path: '/workflow-designer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-results': typeof AccountResultsRoute
  '/agent-configuration': typeof AgentConfigurationRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/new-patterns': typeof NewPatternsRoute
  '/poc-runs': typeof PocRunsRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
  '/workflow-designer': typeof WorkflowDesignerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-results': typeof AccountResultsRoute
  '/agent-configuration': typeof AgentConfigurationRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/new-patterns': typeof NewPatternsRoute
  '/poc-runs': typeof PocRunsRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
  '/workflow-designer': typeof WorkflowDesignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-results': typeof AccountResultsRoute
  '/agent-configuration': typeof AgentConfigurationRoute
  '/data-sources': typeof DataSourcesRoute
  '/login': typeof LoginRoute
  '/mapping-quality': typeof MappingQualityRoute
  '/new-patterns': typeof NewPatternsRoute
  '/poc-runs': typeof PocRunsRoute
  '/project-setup': typeof ProjectSetupRoute
  '/rules': typeof RulesRoute
  '/workflow-designer': typeof WorkflowDesignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-results'
    | '/agent-configuration'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/new-patterns'
    | '/poc-runs'
    | '/project-setup'
    | '/rules'
    | '/workflow-designer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-results'
    | '/agent-configuration'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/new-patterns'
    | '/poc-runs'
    | '/project-setup'
    | '/rules'
    | '/workflow-designer'
  id:
    | '__root__'
    | '/'
    | '/account-results'
    | '/agent-configuration'
    | '/data-sources'
    | '/login'
    | '/mapping-quality'
    | '/new-patterns'
    | '/poc-runs'
    | '/project-setup'
    | '/rules'
    | '/workflow-designer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountResultsRoute: typeof AccountResultsRoute
  AgentConfigurationRoute: typeof AgentConfigurationRoute
  DataSourcesRoute: typeof DataSourcesRoute
  LoginRoute: typeof LoginRoute
  MappingQualityRoute: typeof MappingQualityRoute
  NewPatternsRoute: typeof NewPatternsRoute
  PocRunsRoute: typeof PocRunsRoute
  ProjectSetupRoute: typeof ProjectSetupRoute
  RulesRoute: typeof RulesRoute
  WorkflowDesignerRoute: typeof WorkflowDesignerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-results': {
      id: '/account-results'
      path: '/account-results'
      fullPath: '/account-results'
      preLoaderRoute: typeof AccountResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-configuration': {
      id: '/agent-configuration'
      path: '/agent-configuration'
      fullPath: '/agent-configuration'
      preLoaderRoute: typeof AgentConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping-quality': {
      id: '/mapping-quality'
      path: '/mapping-quality'
      fullPath: '/mapping-quality'
      preLoaderRoute: typeof MappingQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patterns': {
      id: '/new-patterns'
      path: '/new-patterns'
      fullPath: '/new-patterns'
      preLoaderRoute: typeof NewPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc-runs': {
      id: '/poc-runs'
      path: '/poc-runs'
      fullPath: '/poc-runs'
      preLoaderRoute: typeof PocRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-setup': {
      id: '/project-setup'
      path: '/project-setup'
      fullPath: '/project-setup'
      preLoaderRoute: typeof ProjectSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-designer': {
      id: '/workflow-designer'
      path: '/workflow-designer'
      fullPath: '/workflow-designer'
      preLoaderRoute: typeof WorkflowDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountResultsRoute: AccountResultsRoute,
  AgentConfigurationRoute: AgentConfigurationRoute,
  DataSourcesRoute: DataSourcesRoute,
  LoginRoute: LoginRoute,
  MappingQualityRoute: MappingQualityRoute,
  NewPatternsRoute: NewPatternsRoute,
  PocRunsRoute: PocRunsRoute,
  ProjectSetupRoute: ProjectSetupRoute,
  RulesRoute: RulesRoute,
  WorkflowDesignerRoute: WorkflowDesignerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
